name: Build Documentation

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              name: Check out source-code repository
              with:
                  submodules: "true"
                  token: "${{ secrets.CT_SYNC_TOKEN }}"

            - name: Install poetry
              run: pipx install poetry

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"
                  cache: "poetry"

            - name: Disable Poetry virtual environment
              run: poetry config virtualenvs.create false

            - name: Install ehrapy with docs
              run: poetry install --with docs

            - name: Install Pandoc
              run: sudo apt install pandoc

            - name: Build docs
              run: |
                  cd docs
                  poetry run sphinx-build -b html . _build

            - name: Deploy
              if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'}}
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./docs/_build/html
